allowBuilds:
  "@swc/core": true
  esbuild: true
catalog:
  vite: npm:@voidzero-dev/vite-plus-core@1.0.0
  vite-plus: 1.0.0
minimumReleaseAgeExclude:
  - "@oxc-transform/*"
  - oxc-transform
  - oxbox@0.1.0
overrides:
  vite: "catalog:"
peerDependencyRules:
  allowAny:
    - vite
  allowedVersions:
    vite: "*"
verifyDepsBeforeRun: install
