allowBuilds:
  "@swc/core": true
  esbuild: true
catalog:
  vite: npm:@voidzero-dev/vite-plus-core@0.2.5
  vite-plus: 0.2.6
minimumReleaseAgeExclude:
  - "@oxc-transform/*"
  - oxc-transform
overrides:
  vite: "catalog:"
peerDependencyRules:
  allowAny:
    - vite
  allowedVersions:
    vite: "*"
verifyDepsBeforeRun: install
